version: '3'
services:
  fuzzer:
    platform: linux/amd64
    build:
      context: ./afl
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./corpus:/app/corpus
      - ./findings:/app/findings
    working_dir: /app
    environment:
      - AFL_SKIP_CPUFREQ=1
      - AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1
    command: /bin/bash
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
